sbt "runMain vexiiriscv.tester.TestBench \
    --with-rvc \
    --with-rvf \
    --with-mul \
    --with-div \
    --with-late-alu \
    --allow-bypass-from 0 \
    --div-radix 4 \
    --lsu-l1 \
    --fetch-l1 \
    --with-btb \
    --load-elf $1 \
    --no-rvls-check \
    --print-stats"