#!/usr/bin/env python3
"""Convert merged LLaMa ablation CSV data to a TikZ/PGFPlots line figure."""

from __future__ import annotations

import argparse
import csv
from collections import defaultdict
from pathlib import Path
from typing import Dict, Iterable, List, Optional, Sequence, Tuple


REPO = Path(__file__).resolve().parents[3]
DEFAULT_CSV = REPO / "hw/VexiiMico/benchmark_results/e2e_llama_standard_ablation_large_fpu_3m_28m_merged/merged_results.csv"
DEFAULT_OUT = REPO / "hw/VexiiMico/benchmark_results/e2e_llama_standard_ablation_large_fpu_3m_28m_merged/llama_ablation_throughput.tikz"

PATH_ORDER = (
    "baseline_fp32_kv",
    "bncfu256_noquant_fp32_kv",
    "bncfu256_noquant_kivi_kv",
    "bncfu256_quant64_kivi_kv",
)

PATH_LABELS = {
    "baseline_fp32_kv": "Baseline FP32 Attn",
    "bncfu256_noquant_fp32_kv": "BNCFU256 FP32 Attn",
    "bncfu256_noquant_kivi_kv": "BNCFU256 KIVI Attn",
    "bncfu256_quant64_kivi_kv": "BNCFU256 Q64 KIVI",
}

PATH_STYLES = {
    "baseline_fp32_kv": "black, mark=*",
    "bncfu256_noquant_fp32_kv": "blue!70!black, mark=square*",
    "bncfu256_noquant_kivi_kv": "orange!85!black, mark=triangle*",
    "bncfu256_quant64_kivi_kv": "red!75!black, mark=diamond*",
}

PLOT_SPECS = (
    ("3M\\_prefill", "llama3m_w2a8", "actual_prefill_position", "prefill_tokens_per_sec_500mhz", False),
    ("3M\\_decode", "llama3m_w2a8", "actual_decode_position", "decode_tokens_per_sec_500mhz", True),
    ("28M\\_prefill", "llama28m_w2a8", "actual_prefill_position", "prefill_tokens_per_sec_500mhz", False),
    ("28M\\_decode", "llama28m_w2a8", "actual_decode_position", "decode_tokens_per_sec_500mhz", True),
)


def read_rows(path: Path) -> List[Dict[str, str]]:
    with path.open(newline="", encoding="utf-8") as f:
        return list(csv.DictReader(f))


def parse_float(value: object) -> Optional[float]:
    if value is None:
        return None
    text = str(value).strip()
    if text == "":
        return None
    try:
        return float(text)
    except ValueError:
        return None


def tikz_float(value: float) -> str:
    return f"{value:.6g}"


def collect_points(
    rows: Sequence[Dict[str, str]], model: str, path_name: str, x_field: str, y_field: str
) -> List[Tuple[float, float]]:
    points_by_x: Dict[float, List[float]] = defaultdict(list)
    for row in rows:
        if row.get("merge_success", "1") != "1":
            continue
        if row.get("model") != model or row.get("ablation_path") != path_name:
            continue
        x = parse_float(row.get(x_field))
        y = parse_float(row.get(y_field))
        if x is None or y is None:
            continue
        points_by_x[x].append(y)

    points: List[Tuple[float, float]] = []
    for x, values in sorted(points_by_x.items()):
        points.append((x, sum(values) / len(values)))
    return points


def coordinates(points: Iterable[Tuple[float, float]]) -> str:
    return " ".join(f"({tikz_float(x)},{tikz_float(y)})" for x, y in points)


def axis_limits(rows: Sequence[Dict[str, str]]) -> Tuple[int, int]:
    positions: List[float] = []
    for row in rows:
        for field in ("actual_prefill_position", "actual_decode_position"):
            pos = parse_float(row.get(field))
            if pos is not None:
                positions.append(pos)
    if not positions:
        return 0, 1
    return int(min(positions)), int(max(positions))


def make_tikz(rows: Sequence[Dict[str, str]], caption_comment: str, decode_y_field: str) -> str:
    xmin, xmax = axis_limits(rows)
    lines: List[str] = [
        "% Auto-generated by hw/VexiiMico/tools/llama_ablation_csv_to_tikz.py",
        f"% {caption_comment}",
        "% Requires \\usepackage{pgfplots} and \\usepgfplotslibrary{groupplots}.",
        "\\begin{tikzpicture}",
        "\\begin{groupplot}[",
        "  group style={group size=4 by 1, horizontal sep=1.0cm},",
        "  width=0.245\\textwidth,",
        "  height=0.30\\textwidth,",
        "  xlabel={Position},",
        "  ylabel={Throughput (tok/s)},",
        "  xmin=" + str(xmin) + ", xmax=" + str(xmax) + ",",
        "  grid=both,",
        "  tick align=outside,",
        "  scaled y ticks=false,",
        "  ymajorgrids=true,",
        "  xmajorgrids=true,",
        "  every axis plot/.append style={line width=0.85pt},",
        "  legend style={draw=none, fill=none, font=\\scriptsize, at={(0.02,0.98)}, anchor=north west},",
        "  label style={font=\\scriptsize},",
        "  tick label style={font=\\scriptsize},",
        "  title style={font=\\small},",
        "]",
    ]

    for plot_idx, (title, model, x_field, y_field, is_decode) in enumerate(PLOT_SPECS):
        if is_decode:
            y_field = decode_y_field
        ylabel = "Throughput (tok/s)" if plot_idx == 0 else ""
        lines.append(f"\\nextgroupplot[title={{{title}}}, ylabel={{{ylabel}}}]")
        for path_name in PATH_ORDER:
            points = collect_points(rows, model, path_name, x_field, y_field)
            if not points:
                continue
            style = PATH_STYLES[path_name]
            label = PATH_LABELS[path_name]
            lines.append(f"\\addplot+[ {style} ] coordinates {{{coordinates(points)}}};")
            if plot_idx == 0:
                lines.append(f"\\addlegendentry{{{label}}}")

    lines.extend(["\\end{groupplot}", "\\end{tikzpicture}", ""])
    return "\n".join(lines)


def parse_args() -> argparse.Namespace:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--csv", type=Path, default=DEFAULT_CSV, help="Merged benchmark CSV to plot.")
    parser.add_argument("--out", type=Path, default=DEFAULT_OUT, help="Output TikZ file.")
    parser.add_argument(
        "--decode-mode",
        choices=("group-amortized", "raw"),
        default="group-amortized",
        help="Throughput field used for decode subplots.",
    )
    return parser.parse_args()


def main() -> None:
    args = parse_args()
    rows = read_rows(args.csv)
    decode_y_field = "decode_tokens_per_sec_500mhz"
    if args.decode_mode == "group-amortized":
        decode_y_field = "decode_tokens_per_sec_500mhz_group_amortized"
    tikz = make_tikz(rows, f"source={args.csv}, decode_mode={args.decode_mode}", decode_y_field)
    args.out.parent.mkdir(parents=True, exist_ok=True)
    args.out.write_text(tikz, encoding="utf-8")
    print(f"Read {len(rows)} rows from {args.csv}")
    print(f"Wrote {args.out}")


if __name__ == "__main__":
    main()
